import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import NavBar from "./ui/navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className + " flex flex-col"}>
        <NavBar></NavBar>
        <div className="h-[93vh] place-content-center">{children}</div>
      </body>
    </html>
  );
}
